export const copy = {
  catalog: 'Каталог',
  catalogProjects: 'Каталог проектов',
  viewProject: 'Посмотреть проект',
  share: 'Поделиться',
  favoriteAdd: 'В избранное',
  favoriteRemove: 'Убрать из избранного',
  shareCopied: 'Ссылка скопирована',
  shareFailed: 'Не удалось поделиться',
  priceOnRequest: 'Цена по запросу',
  area: 'Площадь',
  floors: 'Этажность',
  bedrooms: 'Спальни',
  bathrooms: 'Санузлы',
  specArea: 'м²',
  specFloors: 'эт.',
  specBed: 'сп.',
  specBath: 'с/у',
  allProjects: 'Весь каталог',
  filters: 'Фильтры',
  apply: 'Показать',
  reset: 'Сбросить',
  anyFloor: 'Любая этажность',
  production: 'Производство',
  productionHeading: 'Завод Авангард Строй',
  productionBody:
    'Домокомплекты изготавливают на заводе в Нижнем Новгороде: раскрой, покраска, сборка панелей и стропильных ферм. На экскурсии можно пройти по цехам и увидеть линию в работе.',
  productionItems: [
    'Линия с обрабатывающим центром с ЧПУ',
    'Форматно-раскроечный участок плитных обшивок',
    'Портальные линии окрашивания',
    'Линия производства строительных ферм',
  ],
  contacts: 'Контакты',
  contactsEyebrow: 'Связаться',
  contactsBody: 'Напишите или позвоните — ответим по проектам, срокам и стоимости строительства.',
  phoneLabel: 'Телефон',
  emailLabel: 'Email',
  addressLabel: 'Адрес / город',
  haveQuestion: 'Есть вопрос?',
  haveQuestionBody: 'Оставьте контакты — перезвоним и поможем с выбором проекта, сроками и стоимостью.',
  sendLead: 'Задать вопрос',
  askQuestion: 'Задать вопрос',
  askQuestionShort: 'Вопрос',
  name: 'Имя',
  namePlaceholder: 'Как к вам обращаться',
  phone: 'Телефон',
  message: 'Сообщение',
  messagePlaceholder: 'Интересующий проект или вопрос',
  consent: 'Согласен на обработку персональных данных',
  leadOk: 'Заявка отправлена. Мы свяжемся с вами в ближайшее время.',
  leadError: 'Не удалось отправить. Попробуйте ещё раз.',
  sending: 'Отправка…',
  exteriors: 'Фасады',
  interiors: 'Интерьеры',
  floorPlans: 'Планировки',
  quote: 'Расчёт комплектации',
  configurator: 'Комплектация',
  included: 'Включено',
  breadcrumbsHome: 'Главная',
  breadcrumbsCatalog: 'Каталог',
  consult: 'Получить консультацию',
  close: 'Закрыть',
  factoryTour: 'Записаться на экскурсию',
  factoryAlt: 'Производство модульных и каркасных домов',
  factoryVideoTitle: 'Завод «Авангард Строй»',
  factoryWatchLabel: 'Посмотреть видео с производства',
  factoryWatch: 'Смотреть',
  previewBanner: 'Черновик. Страница не индексируется.',
  exitPreview: 'Выйти из preview',
  pageUnpublished: 'Страница не опубликована.',
  unknownBlock: 'Неизвестный блок',
  noPhoto: 'Нет фото',
  menu: 'Меню',
  catalogFooter: 'Каталог',
  modularHouses: 'Модульные дома',
  frameHouses: 'Панельно-каркасные дома',
  privacy: 'Политика конфиденциальности',
  offerDisclaimer:
    'Информация, опубликованная на сайте предназначена для ознакомительных целей и не является публичной офертой, определяемой положениями Статьи 437 (2) ГК РФ',
  footerAbout: 'Avangard Stroy помогает выбрать проект, рассчитать смету и построить дом.',
  heroHeadline:
    'Строим современные каркасные и модульные дома для комфортной жизни, отдыха и постоянного проживания',
  heroText:
    'Собственное производство, современные технологии строительства и опытная команда позволяют контролировать качество на каждом этапе, соблюдать сроки и создавать дома на долгие годы.',
  popularEyebrow: 'Популярные',
  popularHeading: 'Проекты домов',
  catalogCta: 'Каталог',
  seoTitle: 'Avangard Stroy — строительство домов',
  seoDescription: 'Avangard Stroy: проекты домов, расчёт стоимости и строительство.',
  notFound: 'Страница не найдена',
} as const

export function footerAboutFor(name: string): string {
  return `${name} помогает выбрать проект, рассчитать смету и построить дом.`
}
