export const copy = {
  catalog: 'Каталог',
  viewProject: 'Посмотреть проект',
  share: 'Поделиться',
  favoriteAdd: 'В избранное',
  favoriteRemove: 'Убрать из избранного',
  shareCopied: 'Ссылка скопирована',
  shareFailed: 'Не удалось поделиться',
  priceOnRequest: 'Цена по запросу',
  area: 'Площадь',
  floors: 'Этажность',
  bedrooms: 'Спальни',
  bathrooms: 'Санузлы',
  allProjects: 'Весь каталог',
  filters: 'Фильтры',
  apply: 'Показать',
  reset: 'Сбросить',
  anyFloor: 'Любая этажность',
  production: 'Производство',
  contacts: 'Контакты',
  sendLead: 'Отправить заявку',
  name: 'Имя',
  phone: 'Телефон',
  consent: 'Согласен на обработку персональных данных',
  leadOk: 'Заявка принята. Мы свяжемся.',
  leadError: 'Не удалось отправить. Попробуйте ещё раз.',
  exteriors: 'Фасады',
  interiors: 'Интерьеры',
  floorPlans: 'Планировки',
  quote: 'Расчёт комплектации',
  configurator: 'Комплектация',
  included: 'Включено',
  breadcrumbsHome: 'Главная',
  breadcrumbsCatalog: 'Каталог',
  consult: 'Получить консультацию',
  close: 'Закрыть',
  factoryTour: 'Записаться на экскурсию',
  previewBanner: 'Черновик. Страница не индексируется.',
  exitPreview: 'Выйти из preview',
  pageUnpublished: 'Страница не опубликована.',
  unknownBlock: 'Неизвестный блок',
} as const
