import { formatFromRub } from "../locale"
import type { CatalogProject, CatalogSeries } from "./types"

/**
 * Каталог из папок public/catalog.
 *
 * Серия читается из префикса папки: barn* — барнхаусы,
 * shvedskii/norvegiya/ekohouse — панельно-каркасные,
 * kamelot/uzorye/finlyandiya/scandi — классика,
 * cube/duplex/frame — модульные. Площадь — число в имени.
 * Этажи, спальни и санузлы — с планировок в той же папке.
 */
export const CATALOG_PROJECTS: CatalogProject[] = [
  {
    id: "barhhouse-73",
    slug: "barhhouse-73",
    name: "Барнхаус 73",
    area: "73",
    areaValue: 73,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "1",
    priceLabel: formatFromRub(3650000),
    priceAmount: 3650000,
    imageUrl: "/catalog/barhhouse-73/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "barn",
    technology: "panel",
    href: "/catalog/barhhouse-73",
    description: "Дом в стиле барнхаус площадью 73 м².",
    exteriors: [
      "/catalog/barhhouse-73/01.jpg",
      "/catalog/barhhouse-73/02.webp",
      "/catalog/barhhouse-73/03.jpg",
      "/catalog/barhhouse-73/04.jpg",
      "/catalog/barhhouse-73/05.jpg",
      "/catalog/barhhouse-73/06.jpg",
      "/catalog/barhhouse-73/07.webp",
      "/catalog/barhhouse-73/08.webp",
      "/catalog/barhhouse-73/09.webp",
      "/catalog/barhhouse-73/10.jpg",
      "/catalog/barhhouse-73/11.jpg",
      "/catalog/barhhouse-73/12.jpg",
      "/catalog/barhhouse-73/13.jpg",
      "/catalog/barhhouse-73/14.jpg",
      "/catalog/barhhouse-73/15.jpg",
      "/catalog/barhhouse-73/16.jpg",
      "/catalog/barhhouse-73/17.jpg",
      "/catalog/barhhouse-73/18.jpg",
      "/catalog/barhhouse-73/19.jpg",
      "/catalog/barhhouse-73/20.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "barnhouse-76",
    slug: "barnhouse-76",
    name: "Барнхаус 76",
    area: "76",
    areaValue: 76,
    floors: "1",
    floorsValue: 1,
    bedrooms: "2",
    bathrooms: "1",
    priceLabel: formatFromRub(3800000),
    priceAmount: 3800000,
    imageUrl: "/catalog/barnhouse-76/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "barn",
    technology: "panel",
    href: "/catalog/barnhouse-76",
    description: "Дом в стиле барнхаус площадью 76 м².",
    exteriors: [
      "/catalog/barnhouse-76/01.jpg",
      "/catalog/barnhouse-76/02.jpg",
      "/catalog/barnhouse-76/03.jpg",
      "/catalog/barnhouse-76/04.jpeg",
      "/catalog/barnhouse-76/05.jpg",
      "/catalog/barnhouse-76/06.jpg",
      "/catalog/barnhouse-76/07.jpg",
      "/catalog/barnhouse-76/08.jpg",
      "/catalog/barnhouse-76/09.jpg",
      "/catalog/barnhouse-76/10.jpg",
      "/catalog/barnhouse-76/11.jpg",
      "/catalog/barnhouse-76/12.jpg",
      "/catalog/barnhouse-76/13.jpg",
      "/catalog/barnhouse-76/14.jpg",
      "/catalog/barnhouse-76/15.jpg",
      "/catalog/barnhouse-76/16.jpg",
      "/catalog/barnhouse-76/17.jpg",
      "/catalog/barnhouse-76/18.jpg",
      "/catalog/barnhouse-76/19.jpg",
      "/catalog/barnhouse-76/20.jpg",
      "/catalog/barnhouse-76/21.jpg",
      "/catalog/barnhouse-76/22.jpg",
      "/catalog/barnhouse-76/23.jpg",
      "/catalog/barnhouse-76/24.jpg",
      "/catalog/barnhouse-76/25.jpg",
      "/catalog/barnhouse-76/26.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "barnhuose-82",
    slug: "barnhuose-82",
    name: "Барнхаус 82",
    area: "82",
    areaValue: 82,
    floors: "1",
    floorsValue: 1,
    bedrooms: "2",
    bathrooms: "1",
    priceLabel: formatFromRub(4100000),
    priceAmount: 4100000,
    imageUrl: "/catalog/barnhuose-82/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "barn",
    technology: "panel",
    href: "/catalog/barnhuose-82",
    description: "Дом в стиле барнхаус площадью 82 м².",
    exteriors: [
      "/catalog/barnhuose-82/01.jpg",
      "/catalog/barnhuose-82/02.jpg",
      "/catalog/barnhuose-82/03.jpg",
      "/catalog/barnhuose-82/04.jpg",
      "/catalog/barnhuose-82/05.jpg",
      "/catalog/barnhuose-82/06.jpg",
      "/catalog/barnhuose-82/07.jpg",
      "/catalog/barnhuose-82/08.jpeg",
      "/catalog/barnhuose-82/09.jpg",
      "/catalog/barnhuose-82/10.jpg",
      "/catalog/barnhuose-82/11.jpg",
      "/catalog/barnhuose-82/12.jpg",
      "/catalog/barnhuose-82/13.jpg",
      "/catalog/barnhuose-82/14.jpg",
      "/catalog/barnhuose-82/15.jpg",
      "/catalog/barnhuose-82/16.jpg",
      "/catalog/barnhuose-82/17.jpg",
      "/catalog/barnhuose-82/18.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "barnhouse-86",
    slug: "barnhouse-86",
    name: "Барнхаус 86",
    area: "86",
    areaValue: 86,
    floors: "1",
    floorsValue: 1,
    bedrooms: "2",
    bathrooms: "1",
    priceLabel: formatFromRub(4300000),
    priceAmount: 4300000,
    imageUrl: "/catalog/barnhouse-86/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "barn",
    technology: "panel",
    href: "/catalog/barnhouse-86",
    description: "Дом в стиле барнхаус площадью 86 м².",
    exteriors: [
      "/catalog/barnhouse-86/01.jpg",
      "/catalog/barnhouse-86/02.jpg",
      "/catalog/barnhouse-86/03.jpg",
      "/catalog/barnhouse-86/04.jpg",
      "/catalog/barnhouse-86/05.jpg",
      "/catalog/barnhouse-86/06.jpg",
      "/catalog/barnhouse-86/07.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "barnhouse-90",
    slug: "barnhouse-90",
    name: "Барнхаус 90",
    area: "90",
    areaValue: 90,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "1",
    priceLabel: formatFromRub(4500000),
    priceAmount: 4500000,
    imageUrl: "/catalog/barnhouse-90/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "barn",
    technology: "panel",
    href: "/catalog/barnhouse-90",
    description: "Дом в стиле барнхаус площадью 90 м².",
    exteriors: [
      "/catalog/barnhouse-90/01.jpg",
      "/catalog/barnhouse-90/02.jpg",
      "/catalog/barnhouse-90/03.jpg",
      "/catalog/barnhouse-90/04.jpg",
      "/catalog/barnhouse-90/05.jpg",
      "/catalog/barnhouse-90/06.jpg",
      "/catalog/barnhouse-90/07.jpg",
      "/catalog/barnhouse-90/08.jpg",
      "/catalog/barnhouse-90/09.jpg",
      "/catalog/barnhouse-90/10.jpg",
      "/catalog/barnhouse-90/11.png",
      "/catalog/barnhouse-90/12.jpg",
      "/catalog/barnhouse-90/13.jpg",
      "/catalog/barnhouse-90/14.jpg",
      "/catalog/barnhouse-90/15.jpg",
      "/catalog/barnhouse-90/16.jpg",
      "/catalog/barnhouse-90/17.jpg",
      "/catalog/barnhouse-90/18.jpg",
      "/catalog/barnhouse-90/19.jpg",
      "/catalog/barnhouse-90/20.jpg",
      "/catalog/barnhouse-90/21.jpg",
      "/catalog/barnhouse-90/22.jpg",
      "/catalog/barnhouse-90/23.jpg",
      "/catalog/barnhouse-90/24.jpg",
      "/catalog/barnhouse-90/25.jpg",
      "/catalog/barnhouse-90/26.jpg",
      "/catalog/barnhouse-90/27.jpg",
      "/catalog/barnhouse-90/28.jpg",
      "/catalog/barnhouse-90/29.jpg",
      "/catalog/barnhouse-90/30.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "barnhouse-96",
    slug: "barnhouse-96",
    name: "Барнхаус 96",
    area: "96",
    areaValue: 96,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "1",
    priceLabel: formatFromRub(4800000),
    priceAmount: 4800000,
    imageUrl: "/catalog/barnhouse-96/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "barn",
    technology: "panel",
    href: "/catalog/barnhouse-96",
    description: "Дом в стиле барнхаус площадью 96 м².",
    exteriors: [
      "/catalog/barnhouse-96/01.jpg",
      "/catalog/barnhouse-96/02.jpg",
      "/catalog/barnhouse-96/03.jpg",
      "/catalog/barnhouse-96/04.jpg",
      "/catalog/barnhouse-96/05.jpg",
      "/catalog/barnhouse-96/06.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "barnhouse-98",
    slug: "barnhouse-98",
    name: "Барнхаус 98",
    area: "98",
    areaValue: 98,
    floors: "1",
    floorsValue: 1,
    bedrooms: "1",
    bathrooms: "1",
    priceLabel: formatFromRub(4900000),
    priceAmount: 4900000,
    imageUrl: "/catalog/barnhouse-98/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "barn",
    technology: "panel",
    href: "/catalog/barnhouse-98",
    description: "Дом в стиле барнхаус площадью 98 м².",
    exteriors: [
      "/catalog/barnhouse-98/01.jpg",
      "/catalog/barnhouse-98/02.jpg",
      "/catalog/barnhouse-98/03.jpg",
      "/catalog/barnhouse-98/04.jpg",
      "/catalog/barnhouse-98/05.jpg",
      "/catalog/barnhouse-98/06.jpg",
      "/catalog/barnhouse-98/07.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "barnhouse-115",
    slug: "barnhouse-115",
    name: "Барнхаус 115",
    area: "115",
    areaValue: 115,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(5750000),
    priceAmount: 5750000,
    imageUrl: "/catalog/barnhouse-115/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "barn",
    technology: "panel",
    href: "/catalog/barnhouse-115",
    description: "Дом в стиле барнхаус площадью 115 м².",
    exteriors: [
      "/catalog/barnhouse-115/01.jpg",
      "/catalog/barnhouse-115/02.jpg",
      "/catalog/barnhouse-115/03.jpg",
      "/catalog/barnhouse-115/04.jpg",
      "/catalog/barnhouse-115/05.jpg",
      "/catalog/barnhouse-115/06.jpg",
      "/catalog/barnhouse-115/07.jpg",
      "/catalog/barnhouse-115/08.jpg",
      "/catalog/barnhouse-115/09.jpg",
      "/catalog/barnhouse-115/10.jpg",
      "/catalog/barnhouse-115/11.jpg",
      "/catalog/barnhouse-115/12.jpg",
      "/catalog/barnhouse-115/13.jpg",
      "/catalog/barnhouse-115/14.jpg",
      "/catalog/barnhouse-115/15.jpg",
      "/catalog/barnhouse-115/16.jpg",
      "/catalog/barnhouse-115/17.jpg",
      "/catalog/barnhouse-115/18.jpg",
      "/catalog/barnhouse-115/19.jpg",
      "/catalog/barnhouse-115/20.jpg",
      "/catalog/barnhouse-115/21.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "barnouse-122",
    slug: "barnouse-122",
    name: "Барнхаус 122",
    area: "122",
    areaValue: 122,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "1",
    priceLabel: formatFromRub(6100000),
    priceAmount: 6100000,
    imageUrl: "/catalog/barnouse-122/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "barn",
    technology: "panel",
    href: "/catalog/barnouse-122",
    description: "Дом в стиле барнхаус площадью 122 м².",
    exteriors: [
      "/catalog/barnouse-122/01.jpg",
      "/catalog/barnouse-122/02.jpg",
      "/catalog/barnouse-122/03.jpg",
      "/catalog/barnouse-122/04.jpg",
      "/catalog/barnouse-122/05.jpg",
      "/catalog/barnouse-122/06.jpg",
      "/catalog/barnouse-122/07.jpg",
      "/catalog/barnouse-122/08.jpg",
      "/catalog/barnouse-122/09.jpg",
      "/catalog/barnouse-122/10.jpg",
      "/catalog/barnouse-122/11.jpg",
      "/catalog/barnouse-122/12.jpg",
      "/catalog/barnouse-122/13.jpg",
      "/catalog/barnouse-122/14.jpg",
      "/catalog/barnouse-122/15.jpg",
      "/catalog/barnouse-122/16.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "barnhouse-129",
    slug: "barnhouse-129",
    name: "Барнхаус 129",
    area: "129",
    areaValue: 129,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(6450000),
    priceAmount: 6450000,
    imageUrl: "/catalog/barnhouse-129/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "barn",
    technology: "panel",
    href: "/catalog/barnhouse-129",
    description: "Дом в стиле барнхаус площадью 129 м².",
    exteriors: [
      "/catalog/barnhouse-129/01.png",
      "/catalog/barnhouse-129/02.jpg",
      "/catalog/barnhouse-129/03.jpg",
      "/catalog/barnhouse-129/04.jpg",
      "/catalog/barnhouse-129/05.jpg",
      "/catalog/barnhouse-129/06.jpg",
      "/catalog/barnhouse-129/07.jpg",
      "/catalog/barnhouse-129/08.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "barnhouse-134",
    slug: "barnhouse-134",
    name: "Барнхаус 134",
    area: "134",
    areaValue: 134,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(6700000),
    priceAmount: 6700000,
    imageUrl: "/catalog/barnhouse-134/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "barn",
    technology: "panel",
    href: "/catalog/barnhouse-134",
    description: "Дом в стиле барнхаус площадью 134 м².",
    exteriors: [
      "/catalog/barnhouse-134/01.jpg",
      "/catalog/barnhouse-134/02.jpg",
      "/catalog/barnhouse-134/03.jpg",
      "/catalog/barnhouse-134/04.jpg",
      "/catalog/barnhouse-134/05.jpg",
      "/catalog/barnhouse-134/06.jpg",
      "/catalog/barnhouse-134/07.jpg",
      "/catalog/barnhouse-134/08.jpg",
      "/catalog/barnhouse-134/09.png",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "barnhouse-138",
    slug: "barnhouse-138",
    name: "Барнхаус 138",
    area: "138",
    areaValue: 138,
    floors: "2",
    floorsValue: 2,
    bedrooms: "4",
    bathrooms: "2",
    priceLabel: formatFromRub(6900000),
    priceAmount: 6900000,
    imageUrl: "/catalog/barnhouse-138/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "barn",
    technology: "panel",
    href: "/catalog/barnhouse-138",
    description: "Дом в стиле барнхаус площадью 138 м².",
    exteriors: [
      "/catalog/barnhouse-138/01.jpg",
      "/catalog/barnhouse-138/02.jpeg",
      "/catalog/barnhouse-138/03.jpg",
      "/catalog/barnhouse-138/04.jpeg",
      "/catalog/barnhouse-138/05.jpg",
      "/catalog/barnhouse-138/06.jpg",
      "/catalog/barnhouse-138/07.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "duplex-173",
    slug: "duplex-173",
    name: "Дуплекс 173",
    area: "173",
    areaValue: 173,
    floors: "1",
    floorsValue: 1,
    bedrooms: "4",
    bathrooms: "2",
    priceLabel: formatFromRub(10050000),
    priceAmount: 10050000,
    imageUrl: "/catalog/duplex-173/00.jpg",
    technologyBadge: "Модульный",
    series: "modular",
    technology: "modular",
    href: "/catalog/duplex-173",
    description: "Модульный дом площадью 173 м².",
    exteriors: [
      "/catalog/duplex-173/01.jpg",
      "/catalog/duplex-173/02.jpg",
      "/catalog/duplex-173/03.jpg",
      "/catalog/duplex-173/04.jpg",
      "/catalog/duplex-173/05.jpg",
      "/catalog/duplex-173/06.jpg",
      "/catalog/duplex-173/07.jpg",
      "/catalog/duplex-173/08.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "kamelot-101",
    slug: "kamelot-101",
    name: "Камелот 101",
    area: "101",
    areaValue: 101,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "1",
    priceLabel: formatFromRub(4850000),
    priceAmount: 4850000,
    imageUrl: "/catalog/kamelot-101/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "classic",
    technology: "panel",
    href: "/catalog/kamelot-101",
    description: "Дом классической архитектуры площадью 101 м².",
    exteriors: [
      "/catalog/kamelot-101/01.jpg",
      "/catalog/kamelot-101/02.jpg",
      "/catalog/kamelot-101/03.jpg",
      "/catalog/kamelot-101/04.jpg",
      "/catalog/kamelot-101/05.jpg",
      "/catalog/kamelot-101/06.jpg",
      "/catalog/kamelot-101/07.png",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "kamelot-124",
    slug: "kamelot-124",
    name: "Камелот 124",
    area: "124",
    areaValue: 124,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "1",
    priceLabel: formatFromRub(5950000),
    priceAmount: 5950000,
    imageUrl: "/catalog/kamelot-124/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "classic",
    technology: "panel",
    href: "/catalog/kamelot-124",
    description: "Дом классической архитектуры площадью 124 м².",
    exteriors: [
      "/catalog/kamelot-124/01.jpg",
      "/catalog/kamelot-124/02.jpg",
      "/catalog/kamelot-124/03.jpg",
      "/catalog/kamelot-124/04.jpg",
      "/catalog/kamelot-124/05.jpg",
      "/catalog/kamelot-124/06.jpg",
      "/catalog/kamelot-124/07.jpg",
      "/catalog/kamelot-124/08.png",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "cube-100",
    slug: "cube-100",
    name: "Куб 100",
    area: "100",
    areaValue: 100,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(5800000),
    priceAmount: 5800000,
    imageUrl: "/catalog/cube-100/00.jpg",
    technologyBadge: "Модульный",
    series: "modular",
    technology: "modular",
    href: "/catalog/cube-100",
    description: "Модульный дом площадью 100 м².",
    exteriors: [
      "/catalog/cube-100/01.jpg",
      "/catalog/cube-100/02.jpg",
      "/catalog/cube-100/03.jpg",
      "/catalog/cube-100/04.jpg",
      "/catalog/cube-100/05.jpg",
      "/catalog/cube-100/06.jpg",
      "/catalog/cube-100/07.jpg",
      "/catalog/cube-100/08.jpg",
      "/catalog/cube-100/09.jpg",
      "/catalog/cube-100/10.jpg",
      "/catalog/cube-100/11.jpg",
      "/catalog/cube-100/12.jpg",
      "/catalog/cube-100/13.jpg",
      "/catalog/cube-100/14.jpg",
      "/catalog/cube-100/15.jpg",
      "/catalog/cube-100/16.jpg",
      "/catalog/cube-100/17.jpg",
      "/catalog/cube-100/18.jpg",
      "/catalog/cube-100/19.jpg",
      "/catalog/cube-100/20.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "norvegiya-92",
    slug: "norvegiya-92",
    name: "Норвегия 92",
    area: "92",
    areaValue: 92,
    floors: "1",
    floorsValue: 1,
    bedrooms: "2",
    bathrooms: "1",
    priceLabel: formatFromRub(4800000),
    priceAmount: 4800000,
    imageUrl: "/catalog/norvegiya-92/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "panel",
    technology: "panel",
    href: "/catalog/norvegiya-92",
    description: "Панельно-каркасный дом площадью 92 м².",
    exteriors: [
      "/catalog/norvegiya-92/01.jpg",
      "/catalog/norvegiya-92/02.jpg",
      "/catalog/norvegiya-92/03.jpg",
      "/catalog/norvegiya-92/04.jpg",
      "/catalog/norvegiya-92/05.jpg",
      "/catalog/norvegiya-92/06.jpg",
      "/catalog/norvegiya-92/07.jpg",
      "/catalog/norvegiya-92/08.jpg",
      "/catalog/norvegiya-92/09.jpg",
      "/catalog/norvegiya-92/10.jpg",
      "/catalog/norvegiya-92/11.jpg",
      "/catalog/norvegiya-92/12.jpg",
      "/catalog/norvegiya-92/13.jpg",
      "/catalog/norvegiya-92/14.jpg",
      "/catalog/norvegiya-92/15.jpg",
      "/catalog/norvegiya-92/16.jpg",
      "/catalog/norvegiya-92/17.jpg",
      "/catalog/norvegiya-92/18.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "norvegiya-115",
    slug: "norvegiya-115",
    name: "Норвегия 115",
    area: "115",
    areaValue: 115,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "1",
    priceLabel: formatFromRub(6000000),
    priceAmount: 6000000,
    imageUrl: "/catalog/norvegiya-115/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "panel",
    technology: "panel",
    href: "/catalog/norvegiya-115",
    description: "Панельно-каркасный дом площадью 115 м².",
    exteriors: [
      "/catalog/norvegiya-115/01.jpg",
      "/catalog/norvegiya-115/02.jpg",
      "/catalog/norvegiya-115/03.jpg",
      "/catalog/norvegiya-115/04.jpg",
      "/catalog/norvegiya-115/05.jpg",
      "/catalog/norvegiya-115/06.jpg",
      "/catalog/norvegiya-115/07.jpeg",
      "/catalog/norvegiya-115/08.jpeg",
      "/catalog/norvegiya-115/09.jpeg",
      "/catalog/norvegiya-115/10.jpeg",
      "/catalog/norvegiya-115/11.jpeg",
      "/catalog/norvegiya-115/12.jpeg",
      "/catalog/norvegiya-115/13.jpeg",
      "/catalog/norvegiya-115/14.jpeg",
      "/catalog/norvegiya-115/15.jpeg",
      "/catalog/norvegiya-115/16.jpeg",
      "/catalog/norvegiya-115/17.jpeg",
      "/catalog/norvegiya-115/18.jpeg",
      "/catalog/norvegiya-115/19.jpeg",
      "/catalog/norvegiya-115/20.jpeg",
      "/catalog/norvegiya-115/21.jpeg",
      "/catalog/norvegiya-115/22.jpeg",
      "/catalog/norvegiya-115/23.jpeg",
      "/catalog/norvegiya-115/24.jpeg",
      "/catalog/norvegiya-115/25.jpg",
      "/catalog/norvegiya-115/26.jpg",
      "/catalog/norvegiya-115/27.jpg",
      "/catalog/norvegiya-115/28.jpg",
      "/catalog/norvegiya-115/29.jpg",
      "/catalog/norvegiya-115/30.jpg",
      "/catalog/norvegiya-115/31.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "norvegiya-132",
    slug: "norvegiya-132",
    name: "Норвегия 132",
    area: "132",
    areaValue: 132,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(6850000),
    priceAmount: 6850000,
    imageUrl: "/catalog/norvegiya-132/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "panel",
    technology: "panel",
    href: "/catalog/norvegiya-132",
    description: "Панельно-каркасный дом площадью 132 м².",
    exteriors: [
      "/catalog/norvegiya-132/01.jpg",
      "/catalog/norvegiya-132/02.jpg",
      "/catalog/norvegiya-132/03.jpg",
      "/catalog/norvegiya-132/04.jpeg",
      "/catalog/norvegiya-132/05.jpg",
      "/catalog/norvegiya-132/06.jpg",
      "/catalog/norvegiya-132/07.jpg",
      "/catalog/norvegiya-132/08.jpg",
      "/catalog/norvegiya-132/09.jpg",
      "/catalog/norvegiya-132/10.jpg",
      "/catalog/norvegiya-132/11.jpg",
      "/catalog/norvegiya-132/12.jpg",
      "/catalog/norvegiya-132/13.jpg",
      "/catalog/norvegiya-132/14.jpg",
      "/catalog/norvegiya-132/15.jpg",
      "/catalog/norvegiya-132/16.jpg",
      "/catalog/norvegiya-132/17.jpg",
      "/catalog/norvegiya-132/18.jpeg",
      "/catalog/norvegiya-132/19.jpeg",
      "/catalog/norvegiya-132/20.jpeg",
      "/catalog/norvegiya-132/21.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "scandi-90",
    slug: "scandi-90",
    name: "Сканди 90",
    area: "90",
    areaValue: 90,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "1",
    priceLabel: formatFromRub(4300000),
    priceAmount: 4300000,
    imageUrl: "/catalog/scandi-90/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "classic",
    technology: "panel",
    href: "/catalog/scandi-90",
    description: "Дом классической архитектуры площадью 90 м².",
    exteriors: [
      "/catalog/scandi-90/01.jpg",
      "/catalog/scandi-90/02.jpg",
      "/catalog/scandi-90/03.jpg",
      "/catalog/scandi-90/04.jpg",
      "/catalog/scandi-90/05.jpg",
      "/catalog/scandi-90/06.jpg",
      "/catalog/scandi-90/07.jpg",
      "/catalog/scandi-90/08.jpg",
      "/catalog/scandi-90/09.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "uzorye-115",
    slug: "uzorye-115",
    name: "Узорье 115",
    area: "115",
    areaValue: 115,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(5500000),
    priceAmount: 5500000,
    imageUrl: "/catalog/uzorye-115/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "classic",
    technology: "panel",
    href: "/catalog/uzorye-115",
    description: "Дом классической архитектуры площадью 115 м².",
    exteriors: [
      "/catalog/uzorye-115/01.jpg",
      "/catalog/uzorye-115/02.jpg",
      "/catalog/uzorye-115/03.jpg",
      "/catalog/uzorye-115/04.jpg",
      "/catalog/uzorye-115/05.jpg",
      "/catalog/uzorye-115/06.png",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "uzorye-122",
    slug: "uzorye-122",
    name: "Узорье 122",
    area: "122",
    areaValue: 122,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "1",
    priceLabel: formatFromRub(5850000),
    priceAmount: 5850000,
    imageUrl: "/catalog/uzorye-122/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "classic",
    technology: "panel",
    href: "/catalog/uzorye-122",
    description: "Дом классической архитектуры площадью 122 м².",
    exteriors: [
      "/catalog/uzorye-122/01.jpg",
      "/catalog/uzorye-122/02.jpg",
      "/catalog/uzorye-122/03.jpg",
      "/catalog/uzorye-122/04.jpg",
      "/catalog/uzorye-122/05.jpg",
      "/catalog/uzorye-122/06.png",
      "/catalog/uzorye-122/07.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "uzorye-132",
    slug: "uzorye-132",
    name: "Узорье 132",
    area: "132",
    areaValue: 132,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(6350000),
    priceAmount: 6350000,
    imageUrl: "/catalog/uzorye-132/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "classic",
    technology: "panel",
    href: "/catalog/uzorye-132",
    description: "Дом классической архитектуры площадью 132 м².",
    exteriors: [
      "/catalog/uzorye-132/01.jpg",
      "/catalog/uzorye-132/02.jpg",
      "/catalog/uzorye-132/03.jpg",
      "/catalog/uzorye-132/04.jpg",
      "/catalog/uzorye-132/05.jpg",
      "/catalog/uzorye-132/06.jpeg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "finlyandiya-149",
    slug: "finlyandiya-149",
    name: "Финляндия 149",
    area: "149",
    areaValue: 149,
    floors: "1",
    floorsValue: 1,
    bedrooms: "4",
    bathrooms: "2",
    priceLabel: formatFromRub(7150000),
    priceAmount: 7150000,
    imageUrl: "/catalog/finlyandiya-149/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "classic",
    technology: "panel",
    href: "/catalog/finlyandiya-149",
    description: "Дом классической архитектуры площадью 149 м².",
    exteriors: [
      "/catalog/finlyandiya-149/01.png",
      "/catalog/finlyandiya-149/02.jpg",
      "/catalog/finlyandiya-149/03.jpg",
      "/catalog/finlyandiya-149/04.jpg",
      "/catalog/finlyandiya-149/05.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "frame-59",
    slug: "frame-59",
    name: "Фрейм 59",
    area: "59",
    areaValue: 59,
    floors: "1",
    floorsValue: 1,
    bedrooms: "1",
    bathrooms: "1",
    priceLabel: formatFromRub(3400000),
    priceAmount: 3400000,
    imageUrl: "/catalog/frame-59/00.jpg",
    technologyBadge: "Модульный",
    series: "modular",
    technology: "modular",
    href: "/catalog/frame-59",
    description: "Модульный дом площадью 59 м².",
    exteriors: [
      "/catalog/frame-59/01.jpg",
      "/catalog/frame-59/02.jpg",
      "/catalog/frame-59/03.jpg",
      "/catalog/frame-59/04.jpg",
      "/catalog/frame-59/05.jpg",
      "/catalog/frame-59/06.jpg",
      "/catalog/frame-59/07.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "frame-60",
    slug: "frame-60",
    name: "Фрейм 60",
    area: "60",
    areaValue: 60,
    floors: "1",
    floorsValue: 1,
    bedrooms: "1",
    bathrooms: "1",
    priceLabel: formatFromRub(3500000),
    priceAmount: 3500000,
    imageUrl: "/catalog/frame-60/00.jpg",
    technologyBadge: "Модульный",
    series: "modular",
    technology: "modular",
    href: "/catalog/frame-60",
    description: "Модульный дом площадью 60 м².",
    exteriors: [
      "/catalog/frame-60/01.jpg",
      "/catalog/frame-60/02.jpg",
      "/catalog/frame-60/03.jpg",
      "/catalog/frame-60/04.jpg",
      "/catalog/frame-60/05.jpg",
      "/catalog/frame-60/06.jpg",
      "/catalog/frame-60/07.jpg",
      "/catalog/frame-60/08.jpg",
      "/catalog/frame-60/09.jpg",
      "/catalog/frame-60/10.jpg",
      "/catalog/frame-60/11.jpg",
      "/catalog/frame-60/12.png",
      "/catalog/frame-60/13.jpg",
      "/catalog/frame-60/14.jpg",
      "/catalog/frame-60/15.jpg",
      "/catalog/frame-60/16.jpg",
      "/catalog/frame-60/17.jpg",
      "/catalog/frame-60/18.jpg",
      "/catalog/frame-60/19.jpg",
      "/catalog/frame-60/20.jpg",
      "/catalog/frame-60/21.jpg",
      "/catalog/frame-60/22.png",
      "/catalog/frame-60/23.png",
      "/catalog/frame-60/24.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "shvedskii-121",
    slug: "shvedskii-121",
    name: "Шведский 121",
    area: "121",
    areaValue: 121,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(6300000),
    priceAmount: 6300000,
    imageUrl: "/catalog/shvedskii-121/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "panel",
    technology: "panel",
    href: "/catalog/shvedskii-121",
    description: "Панельно-каркасный дом площадью 121 м².",
    exteriors: [
      "/catalog/shvedskii-121/01.jpg",
      "/catalog/shvedskii-121/02.jpg",
      "/catalog/shvedskii-121/03.jpg",
      "/catalog/shvedskii-121/04.jpg",
      "/catalog/shvedskii-121/05.jpg",
      "/catalog/shvedskii-121/06.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "shvedskii-124",
    slug: "shvedskii-124",
    name: "Шведский 124",
    area: "124",
    areaValue: 124,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(6450000),
    priceAmount: 6450000,
    imageUrl: "/catalog/shvedskii-124/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "panel",
    technology: "panel",
    href: "/catalog/shvedskii-124",
    description: "Панельно-каркасный дом площадью 124 м².",
    exteriors: [
      "/catalog/shvedskii-124/01.jpg",
      "/catalog/shvedskii-124/02.jpg",
      "/catalog/shvedskii-124/03.jpg",
      "/catalog/shvedskii-124/04.jpg",
      "/catalog/shvedskii-124/05.jpg",
      "/catalog/shvedskii-124/06.jpg",
      "/catalog/shvedskii-124/07.png",
      "/catalog/shvedskii-124/08.png",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "shvedskii-130",
    slug: "shvedskii-130",
    name: "Шведский 130",
    area: "130",
    areaValue: 130,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(6750000),
    priceAmount: 6750000,
    imageUrl: "/catalog/shvedskii-130/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "panel",
    technology: "panel",
    href: "/catalog/shvedskii-130",
    description: "Панельно-каркасный дом площадью 130 м².",
    exteriors: [
      "/catalog/shvedskii-130/01.jpg",
      "/catalog/shvedskii-130/02.jpg",
      "/catalog/shvedskii-130/03.jpg",
      "/catalog/shvedskii-130/04.jpg",
      "/catalog/shvedskii-130/05.jpg",
      "/catalog/shvedskii-130/06.jpg",
      "/catalog/shvedskii-130/07.jpg",
      "/catalog/shvedskii-130/08.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "shvedskii-135",
    slug: "shvedskii-135",
    name: "Шведский 135",
    area: "135",
    areaValue: 135,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(7000000),
    priceAmount: 7000000,
    imageUrl: "/catalog/shvedskii-135/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "panel",
    technology: "panel",
    href: "/catalog/shvedskii-135",
    description: "Панельно-каркасный дом площадью 135 м².",
    exteriors: [
      "/catalog/shvedskii-135/01.jpg",
      "/catalog/shvedskii-135/02.png",
      "/catalog/shvedskii-135/03.png",
      "/catalog/shvedskii-135/04.jpg",
      "/catalog/shvedskii-135/05.jpg",
      "/catalog/shvedskii-135/06.jpg",
      "/catalog/shvedskii-135/07.jpg",
      "/catalog/shvedskii-135/08.jpg",
      "/catalog/shvedskii-135/09.jpg",
      "/catalog/shvedskii-135/10.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "shvedskii-142",
    slug: "shvedskii-142",
    name: "Шведский 142",
    area: "142",
    areaValue: 142,
    floors: "2",
    floorsValue: 2,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(7400000),
    priceAmount: 7400000,
    imageUrl: "/catalog/shvedskii-142/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "panel",
    technology: "panel",
    href: "/catalog/shvedskii-142",
    description: "Панельно-каркасный дом площадью 142 м².",
    exteriors: [
      "/catalog/shvedskii-142/01.jpg",
      "/catalog/shvedskii-142/02.jpg",
      "/catalog/shvedskii-142/03.jpg",
      "/catalog/shvedskii-142/04.jpg",
      "/catalog/shvedskii-142/05.jpg",
      "/catalog/shvedskii-142/06.jpg",
      "/catalog/shvedskii-142/07.jpg",
      "/catalog/shvedskii-142/08.png",
      "/catalog/shvedskii-142/09.png",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "shvedskii-150",
    slug: "shvedskii-150",
    name: "Шведский 150",
    area: "150",
    areaValue: 150,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(7800000),
    priceAmount: 7800000,
    imageUrl: "/catalog/shvedskii-150/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "panel",
    technology: "panel",
    href: "/catalog/shvedskii-150",
    description: "Панельно-каркасный дом площадью 150 м².",
    exteriors: [
      "/catalog/shvedskii-150/01.jpg",
      "/catalog/shvedskii-150/02.jpeg",
      "/catalog/shvedskii-150/03.jpg",
      "/catalog/shvedskii-150/04.jpg",
      "/catalog/shvedskii-150/05.jpg",
      "/catalog/shvedskii-150/06.jpg",
      "/catalog/shvedskii-150/07.jpg",
      "/catalog/shvedskii-150/08.jpg",
      "/catalog/shvedskii-150/09.jpg",
      "/catalog/shvedskii-150/10.jpg",
      "/catalog/shvedskii-150/11.jpg",
      "/catalog/shvedskii-150/12.jpg",
      "/catalog/shvedskii-150/13.jpg",
      "/catalog/shvedskii-150/14.jpg",
      "/catalog/shvedskii-150/15.jpg",
      "/catalog/shvedskii-150/16.jpg",
      "/catalog/shvedskii-150/17.jpg",
      "/catalog/shvedskii-150/18.jpg",
      "/catalog/shvedskii-150/19.jpg",
      "/catalog/shvedskii-150/20.jpg",
      "/catalog/shvedskii-150/21.jpg",
      "/catalog/shvedskii-150/22.jpg",
      "/catalog/shvedskii-150/23.jpg",
      "/catalog/shvedskii-150/24.jpg",
      "/catalog/shvedskii-150/25.jpg",
      "/catalog/shvedskii-150/26.jpg",
      "/catalog/shvedskii-150/27.jpg",
      "/catalog/shvedskii-150/28.jpg",
      "/catalog/shvedskii-150/29.jpg",
      "/catalog/shvedskii-150/30.jpg",
      "/catalog/shvedskii-150/31.jpg",
      "/catalog/shvedskii-150/32.jpg",
      "/catalog/shvedskii-150/33.jpg",
      "/catalog/shvedskii-150/34.jpg",
      "/catalog/shvedskii-150/35.jpg",
      "/catalog/shvedskii-150/37.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "shvedskii-161",
    slug: "shvedskii-161",
    name: "Шведский 161",
    area: "161",
    areaValue: 161,
    floors: "1",
    floorsValue: 1,
    bedrooms: "4",
    bathrooms: "2",
    priceLabel: formatFromRub(8350000),
    priceAmount: 8350000,
    imageUrl: "/catalog/shvedskii-161/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "panel",
    technology: "panel",
    href: "/catalog/shvedskii-161",
    description: "Панельно-каркасный дом площадью 161 м².",
    exteriors: [
      "/catalog/shvedskii-161/01.jpg",
      "/catalog/shvedskii-161/02.jpg",
      "/catalog/shvedskii-161/03.jpg",
      "/catalog/shvedskii-161/04.jpg",
      "/catalog/shvedskii-161/05.jpg",
      "/catalog/shvedskii-161/06.jpg",
      "/catalog/shvedskii-161/07.jpg",
      "/catalog/shvedskii-161/08.jpg",
      "/catalog/shvedskii-161/09.jpg",
      "/catalog/shvedskii-161/10.jpg",
      "/catalog/shvedskii-161/11.jpg",
      "/catalog/shvedskii-161/12.png",
      "/catalog/shvedskii-161/13.jpg",
      "/catalog/shvedskii-161/14.jpg",
      "/catalog/shvedskii-161/15.jpg",
      "/catalog/shvedskii-161/16.jpg",
      "/catalog/shvedskii-161/17.jpg",
      "/catalog/shvedskii-161/18.jpg",
      "/catalog/shvedskii-161/19.jpg",
      "/catalog/shvedskii-161/20.jpg",
      "/catalog/shvedskii-161/21.jpg",
      "/catalog/shvedskii-161/22.jpg",
      "/catalog/shvedskii-161/23.jpg",
      "/catalog/shvedskii-161/24.jpg",
      "/catalog/shvedskii-161/25.jpg",
      "/catalog/shvedskii-161/26.jpg",
      "/catalog/shvedskii-161/27.jpg",
      "/catalog/shvedskii-161/28.jpg",
      "/catalog/shvedskii-161/29.jpg",
      "/catalog/shvedskii-161/30.jpg",
      "/catalog/shvedskii-161/31.jpg",
      "/catalog/shvedskii-161/32.jpg",
      "/catalog/shvedskii-161/33.jpg",
      "/catalog/shvedskii-161/34.jpg",
      "/catalog/shvedskii-161/35.jpg",
      "/catalog/shvedskii-161/36.jpg",
      "/catalog/shvedskii-161/37.jpg",
      "/catalog/shvedskii-161/38.jpg",
      "/catalog/shvedskii-161/39.jpg",
      "/catalog/shvedskii-161/40.jpg",
      "/catalog/shvedskii-161/41.jpg",
      "/catalog/shvedskii-161/42.jpg",
      "/catalog/shvedskii-161/43.jpg",
      "/catalog/shvedskii-161/44.jpg",
      "/catalog/shvedskii-161/45.jpg",
      "/catalog/shvedskii-161/46.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "ekohouse-120",
    slug: "ekohouse-120",
    name: "Экохаус 120",
    area: "120",
    areaValue: 120,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(6250000),
    priceAmount: 6250000,
    imageUrl: "/catalog/ekohouse-120/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "panel",
    technology: "panel",
    href: "/catalog/ekohouse-120",
    description: "Панельно-каркасный дом площадью 120 м².",
    exteriors: [
      "/catalog/ekohouse-120/01.jpg",
      "/catalog/ekohouse-120/02.jpg",
      "/catalog/ekohouse-120/03.jpg",
      "/catalog/ekohouse-120/04.jpg",
      "/catalog/ekohouse-120/05.jpg",
      "/catalog/ekohouse-120/06.jpg",
      "/catalog/ekohouse-120/07.jpg",
      "/catalog/ekohouse-120/08.jpg",
      "/catalog/ekohouse-120/09.png",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "ekohouse-128",
    slug: "ekohouse-128",
    name: "Экохаус 128",
    area: "128",
    areaValue: 128,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(6650000),
    priceAmount: 6650000,
    imageUrl: "/catalog/ekohouse-128/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "panel",
    technology: "panel",
    href: "/catalog/ekohouse-128",
    description: "Панельно-каркасный дом площадью 128 м².",
    exteriors: [
      "/catalog/ekohouse-128/01.jpg",
      "/catalog/ekohouse-128/02.jpg",
      "/catalog/ekohouse-128/03.jpg",
      "/catalog/ekohouse-128/04.jpg",
      "/catalog/ekohouse-128/05.jpg",
      "/catalog/ekohouse-128/06.jpg",
      "/catalog/ekohouse-128/07.jpg",
      "/catalog/ekohouse-128/08.jpg",
      "/catalog/ekohouse-128/09.jpg",
      "/catalog/ekohouse-128/10.jpg",
      "/catalog/ekohouse-128/11.jpg",
      "/catalog/ekohouse-128/12.jpg",
      "/catalog/ekohouse-128/13.jpg",
      "/catalog/ekohouse-128/14.jpg",
      "/catalog/ekohouse-128/15.jpg",
      "/catalog/ekohouse-128/16.jpg",
      "/catalog/ekohouse-128/17.jpg",
      "/catalog/ekohouse-128/18.jpg",
      "/catalog/ekohouse-128/19.jpg",
      "/catalog/ekohouse-128/20.jpg",
      "/catalog/ekohouse-128/21.jpg",
      "/catalog/ekohouse-128/22.jpg",
      "/catalog/ekohouse-128/23.jpg",
      "/catalog/ekohouse-128/24.jpg",
      "/catalog/ekohouse-128/25.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "ekohouse-132",
    slug: "ekohouse-132",
    name: "Экохаус 132",
    area: "132",
    areaValue: 132,
    floors: "1",
    floorsValue: 1,
    bedrooms: "3",
    bathrooms: "2",
    priceLabel: formatFromRub(6850000),
    priceAmount: 6850000,
    imageUrl: "/catalog/ekohouse-132/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "panel",
    technology: "panel",
    href: "/catalog/ekohouse-132",
    description: "Панельно-каркасный дом площадью 132 м².",
    exteriors: [
      "/catalog/ekohouse-132/01.jpg",
      "/catalog/ekohouse-132/02.jpg",
      "/catalog/ekohouse-132/03.jpg",
      "/catalog/ekohouse-132/04.jpg",
      "/catalog/ekohouse-132/05.jpg",
      "/catalog/ekohouse-132/06.jpg",
      "/catalog/ekohouse-132/07.jpg",
      "/catalog/ekohouse-132/08.jpg",
      "/catalog/ekohouse-132/09.jpg",
      "/catalog/ekohouse-132/10.jpg",
      "/catalog/ekohouse-132/11.jpg",
      "/catalog/ekohouse-132/12.jpg",
      "/catalog/ekohouse-132/13.jpg",
      "/catalog/ekohouse-132/14.jpg",
      "/catalog/ekohouse-132/15.jpg",
      "/catalog/ekohouse-132/16.jpg",
      "/catalog/ekohouse-132/17.jpg",
      "/catalog/ekohouse-132/18.jpg",
      "/catalog/ekohouse-132/19.jpg",
      "/catalog/ekohouse-132/20.jpg",
      "/catalog/ekohouse-132/21.jpg",
      "/catalog/ekohouse-132/22.jpg",
      "/catalog/ekohouse-132/23.jpg",
      "/catalog/ekohouse-132/24.jpg",
      "/catalog/ekohouse-132/25.jpg",
      "/catalog/ekohouse-132/26.jpg",
      "/catalog/ekohouse-132/28.jpg",
      "/catalog/ekohouse-132/29.jpg",
      "/catalog/ekohouse-132/30.jpg",
      "/catalog/ekohouse-132/31.jpg",
      "/catalog/ekohouse-132/32.jpg",
      "/catalog/ekohouse-132/33.jpg",
      "/catalog/ekohouse-132/34.jpg",
      "/catalog/ekohouse-132/35.jpg",
      "/catalog/ekohouse-132/36.jpg",
      "/catalog/ekohouse-132/37.jpg",
      "/catalog/ekohouse-132/38.jpg",
      "/catalog/ekohouse-132/39.jpg",
      "/catalog/ekohouse-132/40.jpg",
      "/catalog/ekohouse-132/41.jpg",
      "/catalog/ekohouse-132/42.jpg",
      "/catalog/ekohouse-132/43.jpg",
      "/catalog/ekohouse-132/44.jpg",
      "/catalog/ekohouse-132/45.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
  {
    id: "ekohouse-184",
    slug: "ekohouse-184",
    name: "Экохаус 184",
    area: "184",
    areaValue: 184,
    floors: "2",
    floorsValue: 2,
    bedrooms: "4",
    bathrooms: "2",
    priceLabel: formatFromRub(9550000),
    priceAmount: 9550000,
    imageUrl: "/catalog/ekohouse-184/00.jpg",
    technologyBadge: "Панельно-каркасный",
    series: "panel",
    technology: "panel",
    href: "/catalog/ekohouse-184",
    description: "Панельно-каркасный дом площадью 184 м².",
    exteriors: [
      "/catalog/ekohouse-184/01.jpg",
      "/catalog/ekohouse-184/02.jpg",
      "/catalog/ekohouse-184/03.jpg",
      "/catalog/ekohouse-184/04.jpg",
      "/catalog/ekohouse-184/05.jpg",
      "/catalog/ekohouse-184/06.jpg",
    ],
    interiors: [],
    floorPlans: [],
    options: [],
  },
]

export function countBySeries(series: CatalogSeries): number {
  return CATALOG_PROJECTS.filter((item) => item.series === series).length
}

