/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    sites: Site;
    pages: Page;
    leads: Lead;
    'project-content': ProjectContent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'project-content': ProjectContentSelect<false> | ProjectContentSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'super-admin' | 'hq-admin' | 'hq-editor' | 'partner-owner' | 'partner-editor' | 'viewer';
  /**
   * Stable partner id from the operational system. Empty for HQ users.
   */
  partnerExternalId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  name: string;
  code: string;
  type: 'corporate' | 'partner' | 'regional' | 'campaign';
  status: 'draft' | 'published' | 'archived';
  subdomain?: string | null;
  customDomains?:
    | {
        hostname: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Operational partner id. Required for partner sites.
   */
  partnerExternalId?: string | null;
  brand?: {
    logo?: (number | null) | Media;
    mobileLogo?: (number | null) | Media;
    favicon?: (number | null) | Media;
    permittedTheme?: ('light' | 'dark' | 'brand') | null;
  };
  contacts?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
  };
  socialLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  navigation?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footer?: {
    legal?: string | null;
  };
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  site: number | Site;
  title: string;
  slug: string;
  pageType: 'content' | 'product' | 'application';
  isHome?: boolean | null;
  parent?: (number | null) | Page;
  /**
   * Unique within a site. Computed from parent + slug.
   */
  fullPath?: string | null;
  layout?:
    | (
        | HeroBlock
        | PopularProjectsBlock
        | TextSectionBlock
        | CtaBlock
        | ProductionSectionBlock
        | ContactsSectionBlock
        | LeadFormBlock
        | ProjectsCatalogBlock
        | FaqBlock
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
    canonical?: string | null;
    robots?: ('index' | 'noindex') | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  heading: string;
  description?: string | null;
  media?: (number | null) | Media;
  theme: 'light' | 'dark' | 'brand';
  size: 'compact' | 'standard' | 'large';
  primaryAction?: {
    label?: string | null;
    href?: string | null;
  };
  secondaryAction?: {
    label?: string | null;
    href?: string | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PopularProjectsBlock".
 */
export interface PopularProjectsBlock {
  eyebrow?: string | null;
  heading: string;
  catalogHref?: string | null;
  catalogLabel?: string | null;
  /**
   * Operational project ids. Empty = fixture default set.
   */
  projectIds?:
    | {
        id: string;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'popularProjects';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextSectionBlock".
 */
export interface TextSectionBlock {
  heading?: string | null;
  body: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock".
 */
export interface CtaBlock {
  heading: string;
  body?: string | null;
  label: string;
  href: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductionSectionBlock".
 */
export interface ProductionSectionBlock {
  eyebrow?: string | null;
  heading: string;
  body: string;
  items?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  media?: (number | null) | Media;
  theme: 'light' | 'dark' | 'brand';
  id?: string | null;
  blockName?: string | null;
  blockType: 'productionSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactsSectionBlock".
 */
export interface ContactsSectionBlock {
  heading: string;
  body?: string | null;
  useSiteContacts?: boolean | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contactsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadFormBlock".
 */
export interface LeadFormBlock {
  heading: string;
  body?: string | null;
  submitLabel?: string | null;
  successText?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'leadForm';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectsCatalogBlock".
 */
export interface ProjectsCatalogBlock {
  heading: string;
  body?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'projectsCatalog';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  heading: string;
  items: {
    question: string;
    answer: string;
    id?: string | null;
  }[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  site: number | Site;
  page?: (number | null) | Page;
  projectExternalId?: string | null;
  sourcePath?: string | null;
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Editorial overlay for an operational project. Do not store prices here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-content".
 */
export interface ProjectContent {
  id: number;
  externalProjectId: string;
  site: number | Site;
  editorialTitle?: string | null;
  editorialDescription?: string | null;
  additionalMedia?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'project-content';
        value: number | ProjectContent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  partnerExternalId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  type?: T;
  status?: T;
  subdomain?: T;
  customDomains?:
    | T
    | {
        hostname?: T;
        id?: T;
      };
  partnerExternalId?: T;
  brand?:
    | T
    | {
        logo?: T;
        mobileLogo?: T;
        favicon?: T;
        permittedTheme?: T;
      };
  contacts?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footer?:
    | T
    | {
        legal?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  pageType?: T;
  isHome?: T;
  parent?: T;
  fullPath?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        popularProjects?: T | PopularProjectsBlockSelect<T>;
        textSection?: T | TextSectionBlockSelect<T>;
        cta?: T | CtaBlockSelect<T>;
        productionSection?: T | ProductionSectionBlockSelect<T>;
        contactsSection?: T | ContactsSectionBlockSelect<T>;
        leadForm?: T | LeadFormBlockSelect<T>;
        projectsCatalog?: T | ProjectsCatalogBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        canonical?: T;
        robots?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  media?: T;
  theme?: T;
  size?: T;
  primaryAction?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryAction?:
    | T
    | {
        label?: T;
        href?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PopularProjectsBlock_select".
 */
export interface PopularProjectsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  catalogHref?: T;
  catalogLabel?: T;
  projectIds?:
    | T
    | {
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextSectionBlock_select".
 */
export interface TextSectionBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CtaBlock_select".
 */
export interface CtaBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  label?: T;
  href?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProductionSectionBlock_select".
 */
export interface ProductionSectionBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  items?:
    | T
    | {
        label?: T;
        id?: T;
      };
  ctaLabel?: T;
  ctaHref?: T;
  media?: T;
  theme?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactsSectionBlock_select".
 */
export interface ContactsSectionBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  useSiteContacts?: T;
  phone?: T;
  email?: T;
  address?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LeadFormBlock_select".
 */
export interface LeadFormBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  submitLabel?: T;
  successText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectsCatalogBlock_select".
 */
export interface ProjectsCatalogBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  site?: T;
  page?: T;
  projectExternalId?: T;
  sourcePath?: T;
  utm?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "project-content_select".
 */
export interface ProjectContentSelect<T extends boolean = true> {
  externalProjectId?: T;
  site?: T;
  editorialTitle?: T;
  editorialDescription?: T;
  additionalMedia?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}